# Generated by Django 4.1.3 on 2022-11-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_etal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etal',
        ),
    ]
